name: Build and tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore .\Synapse.sln

      - name: Test
        run: dotnet test .\Synapse.sln -c Release --no-restore
